// <auto-generated />
namespace Fil_rouge_evente.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class suppression_colonne_fidelite : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(suppression_colonne_fidelite));
        
        string IMigrationMetadata.Id
        {
            get { return "201610041101239_suppression_colonne_fidelite"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
